export const movies = [
  {
    movieName: "퀸메리호: 저주받은 항해",
    movieEngName: "The Queen Mary ",
    code: "",
    year: "2023",
    country: "미국",
    type: "장편",
    genre: "미스터리,공포(호러)",
    status: "개봉예정",
    director: "개리 쇼어",
    producer: "",
  },
  {
    movieName: "문란한 성생활을 즐긴 엄마친구",
    movieEngName: "",
    code: "",
    year: "2024",
    country: "일본",
    type: "장편",
    genre: "성인물(에로)",
    status: "기타",
    director: "",
    producer: "",
  },
  {
    movieName: "선배아내와 바로 눈맞아 속궁합 확인",
    movieEngName: "",
    code: "",
    year: "2024",
    country: "일본",
    type: "장편",
    genre: "성인물(에로)",
    status: "기타",
    director: "",
    producer: "",
  },
  {
    movieName: "매일 늦는 아빠대신 새엄마와 응징섹스",
    movieEngName: "",
    code: "",
    year: "2024",
    country: "일본",
    type: "장편",
    genre: "성인물(에로)",
    status: "기타",
    director: "",
    producer: "",
  },
  {
    movieName: "감도 100퍼센트의 짜릿한 새엄마",
    movieEngName: "",
    code: "",
    year: "2024",
    country: "일본",
    type: "장편",
    genre: "성인물(에로)",
    status: "기타",
    director: "",
    producer: "",
  },
  {
    movieName: "너무 쉽게 삽입을 허락하는 여직원",
    movieEngName: "",
    code: "",
    year: "2025",
    country: "한국",
    type: "장편",
    genre: "성인물(에로)",
    status: "개봉예정",
    director: "",
    producer: "(주)샤이커뮤니케이션즈",
  },
  {
    movieName: "여기 젖어 있어요",
    movieEngName: "",
    code: "",
    year: "2025",
    country: "한국",
    type: "장편",
    genre: "성인물(에로)",
    status: "개봉예정",
    director: "",
    producer: "(주)샤이커뮤니케이션즈",
  },
  {
    movieName: "순진한 가정부와 양아치 사장님",
    movieEngName: "",
    code: "",
    year: "2025",
    country: "한국",
    type: "장편",
    genre: "성인물(에로)",
    status: "개봉예정",
    director: "",
    producer: "(주)샤이커뮤니케이션즈",
  },
  {
    movieName: "겨드랑이 땀냄새가 꼬릿한 새엄마",
    movieEngName: "",
    code: "",
    year: "2024",
    country: "일본",
    type: "장편",
    genre: "성인물(에로)",
    status: "기타",
    director: "",
    producer: "",
  },
  {
    movieName: "대물이라서 헤어질 수가 없어",
    movieEngName: "",
    code: "",
    year: "2025",
    country: "한국",
    type: "장편",
    genre: "성인물(에로)",
    status: "개봉예정",
    director: "",
    producer: "(주)샤이커뮤니케이션즈",
  },
  {
    movieName: "너무 쉽게 가랑이 벌리는 여대생",
    movieEngName: "",
    code: "",
    year: "2025",
    country: "한국",
    type: "장편",
    genre: "성인물(에로)",
    status: "개봉예정",
    director: "",
    producer: "(주)샤이커뮤니케이션즈",
  },
  {
    movieName: "대물에 발정 난 여대생",
    movieEngName: "",
    code: "",
    year: "2025",
    country: "한국",
    type: "장편",
    genre: "성인물(에로)",
    status: "개봉예정",
    director: "",
    producer: "(주)샤이커뮤니케이션즈",
  },
  {
    movieName: "할렐루야 언덕",
    movieEngName: "Hallelujah the Hills",
    code: "",
    year: "1963",
    country: "미국",
    type: "장편",
    genre: "기타",
    status: "기타",
    director: "",
    producer: "",
  },
  {
    movieName: "돼지우리",
    movieEngName: "Pigsty",
    code: "",
    year: "1969",
    country: "프랑스,이탈리아",
    type: "장편",
    genre: "드라마,미스터리",
    status: "기타",
    director: "피에르 파올로 파솔리니",
    producer: "",
  },
  {
    movieName: "마태복음",
    movieEngName: "Il Vangelio Secondo Matteo",
    code: "",
    year: "1964",
    country: "이탈리아",
    type: "장편",
    genre: "드라마,사극",
    status: "개봉",
    director: "피에르 파올로 파솔리니",
    producer: "",
  },
  {
    movieName: "맘마 로마",
    movieEngName: "Mamma Roma",
    code: "",
    year: "1962",
    country: "이탈리아",
    type: "장편",
    genre: "드라마",
    status: "기타",
    director: "피에르 파올로 파솔리니",
    producer: "",
  },
  {
    movieName: "파솔리니의 분노",
    movieEngName: "La Rabbia di Pasolini",
    code: "",
    year: "2008",
    country: "이탈리아",
    type: "장편",
    genre: "다큐멘터리",
    status: "기타",
    director: "피에르 파올로 파솔리니,주세페 베르톨루치",
    producer: "",
  },
  {
    movieName: "살로, 소돔의 120일",
    movieEngName: "Salo, Or The 120 Days Of Sodom",
    code: "",
    year: "1975",
    country: "이탈리아,프랑스",
    type: "장편",
    genre: "드라마",
    status: "기타",
    director: "피에르 파올로 파솔리니",
    producer: "",
  },
  {
    movieName: "나이트 오브 울브즈",
    movieEngName: "Werewolves",
    code: "",
    year: "2024",
    country: "미국",
    type: "장편",
    genre: "액션",
    status: "개봉예정",
    director: "스티븐 C. 밀러",
    producer: "",
  },
  {
    movieName: "2035: 더 그린라이트",
    movieEngName: "2035: The GreenLight",
    code: "",
    year: "2025",
    country: "한국",
    type: "장편",
    genre: "미스터리,스릴러",
    status: "개봉예정",
    director: "박재인",
    producer: "",
  },
  {
    movieName: "극장판 도라에몽: 진구의 그림이야기",
    movieEngName: "Doraemon the Movie: Nobita's Art World Tales",
    code: "",
    year: "2025",
    country: "일본",
    type: "장편",
    genre: "애니메이션",
    status: "개봉예정",
    director: "테라모토 유키요",
    producer: "",
  },
  {
    movieName: "블랙 위도우즈 : 라이센스 투 킬",
    movieEngName: "SNATCHED",
    code: "",
    year: "2024",
    country: "미국",
    type: "장편",
    genre: "액션",
    status: "기타",
    director: "크리스 스톡스",
    producer: "",
  },
];
