import type { Movie } from "./types/movieType";

export const Dmovies: Movie[] = [
  {
    movie_id: 1,
    title: "기생충",
    english_title: "Parasite",
    open_year: 2019,
    type: "Feature",
    status: "Released",
    company: "Barunson E&A",
    directors: ["봉준호"],
    genres: ["Thriller", "Drama"],
    nations: ["South Korea"],
  },
  {
    movie_id: 2,
    title: "인터스텔라",
    english_title: "Interstellar",
    open_year: 2014,
    type: "Feature",
    status: "Released",
    company: "Paramount Pictures",
    directors: ["크리스토퍼 놀란"],
    genres: ["Sci-Fi", "Adventure"],
    nations: ["USA", "UK"],
  },
  {
    movie_id: 3,
    title: "어벤져스: 엔드게임",
    english_title: "Avengers: Endgame",
    open_year: 2019,
    type: "Feature",
    status: "Released",
    company: "Marvel Studios",
    directors: ["안소니 루소", "조 루소"],
    genres: ["Action", "Adventure", "Sci-Fi"],
    nations: ["USA"],
  },
  {
    movie_id: 4,
    title: "라라랜드",
    english_title: "La La Land",
    open_year: 2016,
    type: "Feature",
    status: "Released",
    company: "Summit Entertainment",
    directors: ["데이미언 셔젤"],
    genres: ["Musical", "Romance"],
    nations: ["USA"],
  },
  {
    movie_id: 5,
    title: "기묘한 이야기",
    english_title: "Stranger Things",
    open_year: 2016,
    type: "TV Series",
    status: "Ongoing",
    company: "21 Laps Entertainment",
    directors: ["더퍼 형제"],
    genres: ["Drama", "Fantasy", "Horror"],
    nations: ["USA"],
  },
];
